# Generated by Django 2.1.2 on 2018-10-27 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audiences',
            new_name='Audience',
        ),
    ]
