# Generated by Django 2.1.2 on 2018-10-30 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='media_type',
        ),
        migrations.AddField(
            model_name='card',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.Media'),
        ),
    ]
