# Generated by Django 2.1.2 on 2018-11-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20181030_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='audio',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
