# Generated by Django 2.1.2 on 2019-02-02 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_auto_20181112_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingScoreConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Concept')),
                ('training_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.TrainingScore')),
            ],
        ),
    ]
