# Generated by Django 2.1.2 on 2019-05-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_auto_20190203_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='last_access',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
